name: deploy_frontend

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths: -"frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name funcazureresumearjun2 --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumearjun" --name "azureresumearjun" --resource-group "rg-azure-resume-challenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()